import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <h1 className="text-3xl font-bold underline">
      Hello Platzi!
    </h1>
      </main>
      <footer></footer>
    </>
  )
}
