import Head from 'next/head'
import {  useState } from 'react';
import { MouseEventHandler } from 'react';
import { RandomFox } from '@/components/RandomFox'
import type { NextPage } from 'next';

const random = () => Math.floor(Math.random() * 123) + 1;

// generate simple unique id
const generateId = () => Math.random().toString(36).substr(2,9)

type ImageItems = {id: string; url: string}

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItems>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement>  = (event) => {

    const newImageItem: ImageItems = {
    id: generateId(),
    url: `https://randomfox.ca/images/${random()}.jpg`
  }

  setImages([
    ...images,
    newImageItem
  ])
  }

  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <h1 className="text-3xl font-bold underline">Hello Platzi!</h1>
      <button onClick={addNewFox}>Add new fox</button>
    {images.map(({id, url}) => (
      <div key={id} className='p-4'>
        <RandomFox image={url}/>
      </div>
      
    ))}
   
      </main>
      <footer></footer>
    </>
  )
}


export default Home;